/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MyError, Name } from "./components/my-test-component/my-test-component.types";
export namespace Components {
    interface MyComponentExample {
    }
    interface MyComponentExample2 {
    }
    interface MyTestComponent {
        /**
          * The name data
          * @todo Write better documentation!
         */
        "data": Name;
        /**
          * Set the data of the component
          * @param data the data to set
          * @deprecated This should not be used!
         */
        "setData": (data: Name) => Promise<void>;
    }
}
declare global {
    interface HTMLMyComponentExampleElement extends Components.MyComponentExample, HTMLStencilElement {
    }
    var HTMLMyComponentExampleElement: {
        prototype: HTMLMyComponentExampleElement;
        new (): HTMLMyComponentExampleElement;
    };
    interface HTMLMyComponentExample2Element extends Components.MyComponentExample2, HTMLStencilElement {
    }
    var HTMLMyComponentExample2Element: {
        prototype: HTMLMyComponentExample2Element;
        new (): HTMLMyComponentExample2Element;
    };
    interface HTMLMyTestComponentElement extends Components.MyTestComponent, HTMLStencilElement {
    }
    var HTMLMyTestComponentElement: {
        prototype: HTMLMyTestComponentElement;
        new (): HTMLMyTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component-example": HTMLMyComponentExampleElement;
        "my-component-example2": HTMLMyComponentExample2Element;
        "my-test-component": HTMLMyTestComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponentExample {
    }
    interface MyComponentExample2 {
    }
    interface MyTestComponent {
        /**
          * The name data
          * @todo Write better documentation!
         */
        "data"?: Name;
        /**
          * This is emitted when the component might crash!
         */
        "onCrash"?: (event: CustomEvent<MyError>) => void;
    }
    interface IntrinsicElements {
        "my-component-example": MyComponentExample;
        "my-component-example2": MyComponentExample2;
        "my-test-component": MyTestComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component-example": LocalJSX.MyComponentExample & JSXBase.HTMLAttributes<HTMLMyComponentExampleElement>;
            "my-component-example2": LocalJSX.MyComponentExample2 & JSXBase.HTMLAttributes<HTMLMyComponentExample2Element>;
            "my-test-component": LocalJSX.MyTestComponent & JSXBase.HTMLAttributes<HTMLMyTestComponentElement>;
        }
    }
}
